### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by supernovae** [micahilbery/share-on-mastodon#1]
This is great - much needed.  I'm curious if I couldn't help host a service that would make this more seamless - for example popping up to a webservice if no instance is selected that allows people to quickly search/type an instance in federation and then save that so anyone using this button would get the benefit of a web service helping users make use of it?

**Comment by micahilbery** [comment]
Thank you for the kind words and feedback! While I think that's a neat idea, unfortunately I think something like this bloats the scope and simplicity of this project past what I'm comfortable maintaining.
