### ISSUE TITLE
Allow account name

### ISSUE THREAD

**Issue by gerwitz** [micahilbery/share-on-mastodon#3]
I suspect (without proper UX research) that many users will be confused by federation architecture with _instance_ and _server_. So I prefer "enter your social address" and to discern their instance from that. (This is the default for remote follies on Pleroma/Akkoma, for example.)

This could start by striping everything before the last '@' with #2, but would require a Webfinger lookup to be completely correct. I hope that's possible client-side?

**Comment by micahilbery** [comment]
I think this kinda bloats the scope and simplicity of this particular project past what I'm comfortable maintaining. However, I definitely see the value in cutting out or explaining as much technical jargon as possible. I like "Social Address" as the main identifier words for an instance. I think being a little more explicit in the dialog text with better examples could help with this without the need to make the code more complex.

Maybe something like this:
![CleanShot 2024-02-04 at 16 59 09@2x](https://github.com/micahilbery/share-on-mastodon/assets/10608836/0f53006a-f687-4991-bff3-690d35f662d1)
