### ISSUE TITLE
My share button is on the bottom of my page, so the dialog is off screen

### ISSUE THREAD

**Issue by michaelgwelch** [micahilbery/share-on-mastodon#4]
At first I didn't think the code worked.

This is because the screen went dark but I didn't see a dialog.

Turns out the dialog popped up near the top of my page (off screen) so it wasn't visible.

Any tips on how to customize this?

**Comment by micahilbery** [comment]
I was finally able to reliably reproduce this bug and I believe I have tracked down the cause. I had a leftover unneeded `position` declaration on the dialog and it was causing the dialog to always show at the top of the page not the view. On browsers that don't move the focus automatically (iOS) this meant that the dialog would appear out of view.
